# This workflow will pull kolla ansible docker images from dockerhub, push it to aliyun container registry.
#

# To configure this workflow:
#

# 1. Set up secrets in your workspace: 
#    - ALIYUN_USERNAME with aliyun registry username
#    - ALIYUN_PASSWORD with aliyun registry password
#
# 2. Change the values for the ALIYUN_REGISTRY, ALIYUN_NAMESPACE  environment variables (below).

name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 */4 * * *"
env:
  DOCKER_NAMESPACE: kolla
  KOLLA_BASE_DISTRO: ubuntu
  INSTALL_TYPE: source
  OPENSTACK_RELEASE: wallaby
  ALIYUN_REGISTRY: registry.cn-hangzhou.aliyuncs.com
  ALIYUN_NAMESPACE: ztz_openstack

jobs:
  get-kolla-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Log into aliyun registry
    - name: Log into aliyun registry
      run: echo "2561980937@ztz" | docker login registry.cn-hangzhou.aliyuncs.com --username helloz --password-stdin
      
    # get images list
    - name: get images list
      run: |
        sed -i "s#USER#${{ secrets.ALIYUN_USERNAME }}#g" config.json
        sed -i "s#PASS#${{ secrets.ALIYUN_PASSWORD }}#g" config.json
        wget https://github.com/AliyunContainerService/image-syncer/releases/download/v1.2.0/image-syncer-v1.2.0-linux-amd64.tar.gz
        tar -zxvf image-syncer-v1.2.0-linux-amd64.tar.gz
        ./image-syncer --proc=50 --config=./config.json --registry=registry.cn-shenzhen.aliyuncs.com --namespace=kollaimage --retries=2 --log=./log
